### PR TITLE
PR - Bugfix for graceful closing when MaxConcurrentCalls exceeds 1.

### PR DESCRIPTION
**Pull request by Tankatronic**

### CODE REVIEW

**Comment by Tankatronic** [comment]
In reference to #20

**Comment by loekd** [comment]
Thank you for this contribution @Tankatronic ! 
I've added some changes, please let me know how you feel about those.

**Comment by Tankatronic** [comment]
I like the changes and agree with that refactor for `ListenForMessages`. I didn't like the idea of having to put the initialization logic for the Semaphores in the derived class as that passed the burden on any additional implementations, but I didn't want to go too crazy! Looks good!

**Comment by loekd** [comment]
Yes, you're right. I've made some (potentially breaking) changes to move initialization to where it belongs.
Let me know if that's better, and I'll merge it if `true`.

**Comment by Tankatronic** [comment]
Sorry for the delay, I saw the message but didn't have time to look and forgot later! The changes looked good to me and it feels better having that logic living in the base class now.

**Pull request merged**
